### ISSUE TITLE
Add video demos

### ISSUE THREAD

**Issue by briandowns** [briandowns/super-hacker#3]

**Comment by jaysonesmith** [comment]
A gif(s) would probably be better, yea? There's a really neat tool that I'll have to dig up for this type of thing.

**Comment by briandowns** [comment]
I have 2 videos that I just need to convert to gifs. Uploading this evening. This ticket is a reminder so I don't forget.

**Comment by jaysonesmith** [comment]
Ah, gotcha! I used these in one of my CircleCI posts: [asciinema](https://asciinema.org) with [asciicast2gif](https://github.com/asciinema/asciicast2gif)(use the docker image)

With asciicinema you can fine tune things like speed and whatnot!

Example of one of the ones I did hosted on the product's site:

[![asciicast](https://asciinema.org/a/wSBdVqY53gyPv9C0h0AAMhuK3.svg)](https://asciinema.org/a/wSBdVqY53gyPv9C0h0AAMhuK3)

**Comment by daxmc99** [comment]
I would be interested in seeing this as well
